service: fullstack-lambda-post

package:
  individually: true

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-plugin-monorepo

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: ap-northeast-2
  
  role: ${cf:fullstack-lambda-${self:custom.stage}.IamRole}

  environment:
    TABLENAME: ${self:custom.stage}-fullstackToy
    REGION: ${self:provider.region}
    INVERTINDEX: InvertedIndex
    MODELINDEX: ModelIndex
    GSI1INDEX: GSI1Index


custom:
  webpack:
    webpackConfig: ../../webpack.config.js
    includeModules: true
    forceExclude: 
      - aws-sdk
    
  stage: ${opt:stage, self:provider.stage}

functions:
  updatePost:
    handler: src/handler.updatePostHandler
    events:
      - http:
          path: 'users/{user_id}/posts/{post_id}'
          method: post
          cors: true

  deletePost:
    handler: src/handler.deletePostHandler
    events:
      - http:
          path: 'users/{user_id}/posts/{post_id}'
          method: delete
          cors: true

  putPost:
    handler: src/handler.putPostHandler
    events:
      - http:
          path: 'users/{user_id}/post'
          method: put
          cors: true

  getPostsByUser:
    handler: src/handler.getPostsByUserHandler
    events:
      - http:
          path: 'users/{user_id}/posts'
          method: get
          cors: true

  getPosts:
    handler: src/handler.getPostsHandler
    events:
      - http:
          path: 'posts'
          method: get
          cors: true

  getPostByPostId:
    handler: src/handler.getPostByPostIdHandler
    events:
      - http:
          path: 'posts/{post_id}'
          method: get
          cors: true

resources:
  # GateWay Error
  - ${file(../resources/lambdaResources/api-gateway-error.yml)}
