Resources:
  FullStackToyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.stage}-fullstackToy
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: model
          AttributeType: S
        - AttributeName: GSI1PK
          AttributeType: S
        - AttributeName: GSI1SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}
      GlobalSecondaryIndexes:
        - IndexName: ${self:provider.environment.INVERTINDEX}
          KeySchema:
            - AttributeName: SK
              KeyType: HASH
            - AttributeName: PK
              KeyType: RANGE
          ProvisionedThroughput:
            ReadCapacityUnits: ${self:custom.tableThroughput}
            WriteCapacityUnits: ${self:custom.tableThroughput}
          Projection:
            ProjectionType: "ALL"
        - IndexName: ${self:provider.environment.MODELINDEX}
          KeySchema:
            - AttributeName: model
              KeyType: HASH
          ProvisionedThroughput:
            ReadCapacityUnits: ${self:custom.tableThroughput}
            WriteCapacityUnits: ${self:custom.tableThroughput}
          Projection:
            ProjectionType: "ALL"
        - IndexName: ${self:provider.environment.GSI1INDEX}
          KeySchema:
            - AttributeName: GSI1PK
              KeyType: HASH
            - AttributeName: GSI1SK
              KeyType: RANGE
          ProvisionedThroughput:
            ReadCapacityUnits: ${self:custom.tableThroughput}
            WriteCapacityUnits: ${self:custom.tableThroughput}
          Projection:
            ProjectionType: "ALL"


